# Generated by Django 4.0.3 on 2023-10-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=100)),
                ('eligibility', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('project_type', models.CharField(max_length=500)),
                ('supporting_docs', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('funding_stream', models.CharField(max_length=500)),
            ],
        ),
    ]
