# Generated by Django 4.0.3 on 2023-11-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_stream', models.CharField(max_length=255)),
                ('company_sector', models.CharField(max_length=255)),
                ('estimated_annual_natural_gas_budget', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('employee_count', models.CharField(max_length=255)),
                ('estimated_annual_electricity_budget', models.CharField(max_length=255)),
                ('company_name', models.TextField(blank=True)),
                ('company_contact', models.TextField(blank=True)),
            ],
        ),
    ]
