# Generated by Django 4.2.5 on 2023-11-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_usersearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.CharField(max_length=255)),
                ('contact_company', models.CharField(max_length=255)),
                ('additional_info', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
